version: "3.7"

x-keepalived-defaults: &keepalived-service
  image: "lzh/keepalived_haproxy:v1"
  cap_add:
    - NET_ADMIN
    - NET_BROADCAST
    - NET_RAW
  command: [--copy-service, --loglevel, debug]
  environment:
    KEEPALIVED_COMMAND_LINE_ARGUMENTS: >-
      --log-detail
      --log-console
#      -–dont-release-vrrp
#      -–dont-release-ipvs
#      --log-detail
#      --dump-conf

networks:
  ha-stack:
    name: ha-stack
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

services:
  runner:
    image: "runner:local"
    networks:
      ha-stack:
        ipv4_address: 172.20.0.20
# docker run -it --network=ha-stack runner:local /bin/bash

  proxy-a:
    <<: *keepalived-service
    networks:
      ha-stack:
        ipv4_address: 172.20.0.30
    volumes:
      - "./keepalived/proxy-a/keepalived.conf:/container/service/keepalived/assets/keepalived.conf"
      - "./keepalived/notify.sh:/container/service/keepalived/assets/notify.custom.sh"
      - "./keepalived/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
# chmod 644 keepalived.conf

  proxy-b:
    <<: *keepalived-service
    networks:
      ha-stack:
        ipv4_address: 172.20.0.40
    volumes:
      - "./keepalived/proxy-b/keepalived.conf:/container/service/keepalived/assets/keepalived.conf"
      - "./keepalived/notify.sh:/container/service/keepalived/assets/notify.custom.sh"
      - "./keepalived/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"

  web-b:
    image: "nginx:stable-alpine"
    networks:
      ha-stack:
        aliases:
          - web-b.ha.stack
    volumes:
      - "./web/server-b/index.html:/usr/share/nginx/html/index.html:ro"

  web-a:
    image: "nginx:stable-alpine"
    networks:
      ha-stack:
        aliases:
          - web-a.ha.stack
    volumes:
      - "./web/server-a/index.html:/usr/share/nginx/html/index.html:ro"
